version: '3.8'

services:
  app:
    container_name: app
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - '8080:8080'
    build:
      context: .

  postgres-db:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=news
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'


